### PR TITLE
Buttons

### PR DESCRIPTION
**Pull request by gcstaublin**
### What this did

- [ ] Created new versions of outline variations.
2016-01-28 09 27 22 pm

- [ ] Created custom checkbox versions of button groups. Ultimately it might be worth creating `js` controlled versions of these, as well as additional color options.
2016-01-28 09 27 40 pm
2016-01-28 09 38 25 pm

### CODE REVIEW

**Comment by gcstaublin** [comment]
This one is ready for some eyes and discussion.

**Comment by nick-adams** [comment]
I like those outline types.

Additionally...

There is probably an argument that _all_ buttons should be considered a component, but putting that aside, purely based on our previous definition Id say that your checked buttons can probably be kept out of this partial and instead left for a `button-groups` component since it needs an accompanying .js file to handle the interaction and toggle states. 

Thoughts?

**Comment by gcstaublin** [comment]
I don't know what is best, in the case of the button groups, or any spot where js will be needed to actually hook up the functionality. Including these now at least offers the styles and pattern folks could use with the caveat that they'll need some js to make it functional.

**Comment by nick-adams** [comment]
We could always leave them in there even if we're not quite ready to document them for wide use (until we sort out the best approach).

**Pull request merged**
