### PR TITLE
Add breakpoints and finish the Grid 

### PR DESCRIPTION
**Pull request by nick-adams**
#### What This Did:

* [x] [Added our 4 breakpoints](https://github.com/hudl/pregame/blob/b5f7084ab13d86dcdadb4b567c4f3a15fcd38a23/static/scss/variables/_breakpoints.scss) (small, medium, large, xlarge):
* [x] [Tweaked the media query mixin](https://github.com/hudl/pregame/blob/b5f7084ab13d86dcdadb4b567c4f3a15fcd38a23/static/scss/mixins/_media-query.scss) to account for the breakpoint definitions.
* [x] [Create the behaviors for the columns](https://github.com/hudl/pregame/blob/b5f7084ab13d86dcdadb4b567c4f3a15fcd38a23/static/scss/_grid.scss#L149) at our different breakpoints.
* [x] [Create some Grid helper classes](https://github.com/hudl/pregame/blob/b5f7084ab13d86dcdadb4b567c4f3a15fcd38a23/static/scss/_grid.scss#L195) to hide and show columns at specific breakpoints

**Note**
Our grid is not responsive to the extent that you can add classes to columns that are specific to certain breakpoints (e.g., `.ko-grid-sm__col--*` or `.ko-grid-md__col--*`). Instead our column sizes have _defined_ behaviors at our universal breakpoints. This removes a bit of per-interface control, but also simplifies the use of the grid and ensures consistency.

**To Discuss**
* I need a sanity check on my grid code. It seems like a lot of code in that one partial. Am I missing a good way to simplify this? Am I missing something about the use of `rem` that allows us to change column behaviors more simply? Should we separate the responsive grid styles into a separate partial called `_grid-responsive.scss` or something?
* Do our 4 breakpoints themselves make sense? (I did base this off of our analytics though.)
* Do our column behaviors at each break point make sense? See the `grid-test.html` and `grid-test-gutters.html` pages for examples.

**Feel free to give this all a harsh sanity check...**

### CODE REVIEW

**Comment by gcstaublin** [comment]
Rather than adding line comments, here's a slew of thoughts and questions after playing around with these grids and figuring out how they work.

### ko-grid vs ko-grid__row
I assume the thought is to only use `ko-grid` to wrap all things? And use `ko-grid__row` for each group?

### ko-grid--outsidegutters
I'm not sure if the intent of this class is to provide universal padding, or padding solely within the grid? If it's universal, it's good practice to remove the padding at the point where it's no longer performing a function to keep from weird spacing issues occurring.

### Mobile first
Right now, we define the width of columns, then overwrite those for size 0 to `$small` then restate them at each breakpoint. The width of the columns never change, but are defined a total of 5 times from initial definition through all the breakpoints.

### Issues with fixed width
The fixed width grid breaks at any size that is less than the define width. Because of this, I'd suggest something like
```
width: 100%;
max-width: $grid-max-width;
```

### Media Query
Rather than defining a variable that outlines the media query we should use the existing media query mixin so that we're consistent within the library.


### Insets
It took me awhile to figure out what an inset is designed to accomplish. I'm also not totally sure the need for these. I guess if there are two columns with a larger than usual gutter, these could be of value. Otherwise, I'd would wonder if the spacing could be achieve with a `float: right`?

### Content alignment
If the goal is right or center align all text within a grid, it seems a utility class, abstracted away from grids is more valuable? 

### Hiding content
I know there are instances where hiding an element is ultimately the best thing, versus performing some js gymnastics to move elements around the page. However, I wonder if we want provide out of the box classes that hide stuff? I'd rather folks think longer and harder about hiding a portion of the page than these helpers suggest they would. Thoughts?

**Comment by nick-adams** [comment]
Here are the results of discussing these...

### ko-grid vs ko-grid__row
We're going to keep both for now. `ko-grid__row` still serves a purpose, but the distinction needs to be clearly explained in the documentation.

### ko-grid--outsidegutters
We're going to keep this in there for now. In the future, this may be removed from the grid level options and instead be specifically tied to certain layouts. Layout Template A may have outside gutters on default, etc.

### Mobile first
I will adjust the column definitions to be mobile-first and grow accordingly. 

### Issues with fixed width
I will fix this with the following:
```
width: 100%;
max-width: $grid-max-width;
```

### Media Query
I'll update the media queries to use the mixin, and adjust the mixin based on what we talked about (making it more adaptive to specific device breakpoints than fully responsive).

### Insets
We're going to keep this since they serve a specific purpose.

### Content alignment
These will be abstracted to utility classes.

### Hiding content
These will be kept (for now), but abstracted to utility classes. In the future we may remove these all together and only use them at the Layout Template level (similar to how we'll use outside gutter grid option).

**Comment by gcstaublin** [comment]
Is this waiting on someone to push the big green button? Is that all? I can get this, #64 and #66 merged and see if everything still works.

**Comment by nick-adams** [comment]
Yeah, forgot about this. Its just down to pushing the green button. Feel free to merge this first (probably safest), then merge master into your other PRs as you go.

**Pull request merged**
